name: Deploy to AWS

on:
 push:
   branch:

     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ansible 
        run: | 
          sudo apt install ansible -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Replace SERVER_IP in Ansible inventory

        run: |
          sed -i "s|{{ SERVER_IP }}|${{ secrets.AWS_HOST }}|g" ./ansible/inventory

      - name: Run Ansible playbook on AWS EC2
        working-directory: ${{ github.workspace }}
        run: |
          ansible-playbook -i ./ansible/inventory ./ansible/deploy.yml \
            -u serveurweb \
            --ssh-extra-args "-o StrictHostKeyChecking=no"

